version: '3'
services:
  db:
    image: mysql:8.0
    container_name: court-reserve
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
  php:
    build: php-fpm
    volumes:
      - ./:/var/www/symfony
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/symfony
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  db_data: